### ISSUE TITLE
use skip_on_ci

### ISSUE THREAD

**Issue by tomlue** [biobricks-ai/biobricks-r#10]
```
  has_docker = suppressWarnings(system("docker")) # #TODO use skip_on_ci
```

https://github.com/biobricks-ai/biobrickr/blob/8de4af98feebf99a1dc531d3d988e441dba5bd4c/tests/testthat/test-install-and-bake.R#L12

**Comment by jborden** [comment]
https://github.com/biobricks-ai/biobricks-r/commit/00df6a5772c227d6c7891e3bb254840c0de3a88c satisfies this request
