### ISSUE TITLE
demo bricks

### ISSUE THREAD

**Issue by tomlue** [biobricks-ai/biobricks-r#13]
On wednesday we have a biobricks demo. I will run code like this for each brick:

```R
local_bblib()
brick_install("some-brick")
brick_pull("some-brick") 
brick_load_arrow("some-brick") # or brick_load_sqlite
```

Please ensure this works with:
- [x] hgnc
- [x] dbsnp
- [x] uniprot
- [x] pharmgkb
- [x] clinvar

**Comment by jborden** [comment]
dbSNP is pretty big, over an hour to download.

**Comment by tomlue** [comment]
If a file is > 10gb we should partition it into 1-2gb chunks. This will help with analysis and with download speed. 

The partition should be done so that new versions do not overwrite old versions.

**Comment by jborden** [comment]
Ok I can do that
