### ISSUE TITLE
installation fails with suggested commands

### ISSUE THREAD

**Issue by ReneGeci** [biobricks-ai/biobricks-r#17]
hey, i just tried to install biobricks R, running the suggested first lines and apparently there is a dependency for dvc...

```
> remotes::install_github("biobricks-ai/biobricks-R")
Skipping install of 'biobricks' from a github remote, the SHA1 (f96c8e29) has not changed since last install.
  Use `force = TRUE` to force installation
> biobricks::local_bblib() # OR set a permanent brick dir w/ Sys.setenv(bblib=...) 
Setting deferred event(s) on global environment.
  * Will be run automatically when session ends
  * Execute (and clear) with `withr::deferred_run()`.
  * Clear (without executing) with `withr::deferred_clear()`.
Error in check_has_dvc() : 
  dvc must be installed. See https://dvc.org/doc/install
```

**Comment by tomlue** [comment]
We will update the documentation.  For your own use, you can follow the command in the error which states:
```
Error in check_has_dvc() : 
  dvc must be installed. See https://dvc.org/doc/install
```
Installing biobricks should work after installing DVC with https://dvc.org/doc/install

**Comment by ReneGeci** [comment]
i did install it as suggested [here ](https://dvc.org/doc/install) via pip, the error persists...

**Comment by tomlue** [comment]
dvc needs to be available from the process that biobricks is running in. Could you please try running
```
dvc version
```
in the same terminal you use to start your R process, and let me know the results?

**Comment by ReneGeci** [comment]
i am trying to run it from RStudio, so I am not entirely sure how to check...

however, if i call dvc from the terminal tab in RStudio, it does respond:

```
C:\Users\User\Documents>dvc version
DVC version: 2.12.0 (exe)
---------------------------------
Platform: Python 3.8.10 on Windows-10-10.0.22000-SP0
Supports:
        azure (adlfs = 2022.4.0, knack = 0.9.0, azure-identity = 1.10.0),
        gdrive (pydrive2 = 1.10.1),
        gs (gcsfs = 2022.5.0),
        hdfs (fsspec = 2022.5.0, pyarrow = 8.0.0),
        webhdfs (fsspec = 2022.5.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.5.1),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.5.1),
        s3 (s3fs = 2022.5.0, boto3 = 1.21.21),
        ssh (sshfs = 2022.6.0),
        oss (ossfs = 2021.8.0),
        webdav (webdav4 = 0.9.7),
        webdavs (webdav4 = 0.9.7)
```

**Comment by tomlue** [comment]
@ReneGeci I have updated the check_has_dvc and check_has_git functions to something that should work on windows. Please reinstall biobricks (check `packageVersion("biobricks")` is 0.0.0.9023) and give it another try.

Biobricks-r passes all tests on linux machines, but has not been tested on mac or windows. Please let me know if you run into more issues. 

Hopefully we can add testing options for other OS.

Alternatively, if you have access to a linux or mac environment, you may run into less issues.
